import './globals.css'
import SideBar from '../components/SideBar';
import { ReduxProvider } from '@/redux/provider';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <div className='flex '>
            <SideBar />
            <>
              {children}
            </>
          </div>
        </ReduxProvider>
      </body>
    </html>
  )
}
